### ISSUE TITLE
connection LINE failed

### ISSUE THREAD

**Issue by boztradamuz** [TridentTD/TridentTD_LineNotify#10]
### **Using with PlatformIO**
platform = espressif8266
board = nodemcuv2
framework = arduino

------------------------------------------
### [Log]

<img width="227" alt="image" src="https://user-images.githubusercontent.com/31117258/126887850-9ad735fd-cf4e-41ce-a256-0a77cf45c8d3.png">

- at setup() Line.notify seems to work perfectly fine from TD_DEBUG_PRINT 
`HTTP/1.1 200 `
`HTTP/1.1 200 `

- at loop()
 `SELFCHECK connection Success` from WiFiClientSecure client; (main.cpp)
```
if (!client.connect("notify-api.line.me", 443)) 
    {
      Serial.println("SELFCHECK connection failed\n");
    }
    else
    {
      Serial.println("SELFCHECK connection Success\n");
    }
```

`connection LINE failed` from TD_DEBUG_PRINT

<img width="780" alt="image" src="https://user-images.githubusercontent.com/31117258/126888148-57a7eac3-f7a8-4b8e-9012-2aada3473a20.png">

I tried to use
`WiFiClientSecure _clientSecure;` but will make Line.notify in setup() `connection LINE failed`

**Comment by cychrn** [comment]
เป็นเหมือนกันเลยครับ เป็นหลังจากที่อัพเดท ESP8266 เป็นตัวล่าสุด หลังจากนั้นก็ไม่สามารถใช้งานได้เลยแม้ว่าจะอัพเดทเป็น 3.0.3 แล้วก็ตาม

หลังจากที่ตรวจสอบดูเบื้องต้น ตัว _clientSecure.connect ไม่สามารถทำการเชื่อมต่อ notify-api.line.me ได้ครับ เลยขึ้นว่า connection LINE failed รบกวนขอคำแนะนำหน่อยนะครับผม

ขอบพระคุณมากครับ

**Comment by TridentTD** [comment]
#cychrn 
ใช้ ESP8266 core ไหนอยู่ครับ

**Comment by boztradamuz** [comment]
ของผม Generic ESP8266 (2.7.4) ครับ  ใช้ร่วมกับ  Blynk 1.0.1 ครับ
