### ISSUE TITLE
ถ้าขึ้นแบบนี้ต้องแก้ตรงไหนครับ

### ISSUE THREAD

**Issue by palmna** [TridentTD/TridentTD_LineNotify#11]
error message ครับ
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\Palm\Documents\Arduino\libraries\TridentTD_LineNotify-master\src\TridentTD_LineNotify.cpp:43:10: fatal error: WiFiClientSecureAxTLS.h: No such file or directory

   43 | #include <WiFiClientSecureAxTLS.h>

      |          ^~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by TridentTD** [comment]
ใช้ ESP8266 core ไหนอยู่ครับ?

( เช็คจาก ArduinoIDE ที่เมนู Tools > Boards > Board Manager )
