### ISSUE TITLE
ส่งไฟล์

### ISSUE THREAD

**Issue by icsHaLl** [TridentTD/TridentTD_LineNotify#12]
ไลน์สามารถส่งไฟล์ได้ไหมครับ?

ถ้าส่งได้มีวิธี ตัวอย่าง หรือคำแนะนำไหมครับ

ขอบคุณครับ @TridentTD

**Comment by TridentTD** [comment]
LINE ไม่รองรับส่ง file ครับ
ต้อง นำ file ขึ้น server ที่ฝากไฟล์ทางอื่นเอง
แล้วส่ง line notify ไปบอก url แทน
