### ISSUE TITLE
error: libraries\TridentTD_LineNotify\TridentTD_LineNotify.a: No such file or directory

### ISSUE THREAD

**Issue by mebiol** [TridentTD/TridentTD_LineNotify#15]
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Archiving built core (caching) in: C:\Users\Som\AppData\Local\Temp\arduino_cache_314486\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_aa388067a821a694b2260c380a97f394.a
xtensa-lx106-elf-gcc: error: libraries\TridentTD_LineNotify\TridentTD_LineNotify.a: No such file or directory

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

ลงใหม่ 2-3 รอบแล้ว ทั้ง Add zip แล้วก็ extract file ใส่เองยังเป็นเหมือนเดิมเลยค่ะ

**Comment by TridentTD** [comment]
ArduinoIDE 1.8.5 เก่ามากไปแล้ว
ให้ลง ArduinoIDE 1.8.19  ล่าสุดของ ArduinoIDE 1.8.x แทน
แล้วลง Arduino ESP8266 core ล่าสุดก็จะใช้งานได้
