### ISSUE TITLE
please add function send picture by esp32

### ISSUE THREAD

**Issue by pasagame** [TridentTD/TridentTD_LineNotify#3]
i use esp32 and ov2640 i want function line picture notify by esp32. you can look example from [https://github.com/LilyGO/ESP32-Camera/blob/master/examples/BIGIOT_UpdateImage/BIGIOT_UpdateImage.ino](url) thank you verry much.

**Comment by TridentTD** [comment]
Update to version 3.0
support send Line Notify by jpg file or jpg data from camera

https://github.com/TridentTD/TridentTD_LineNotify/releases/tag/3.0

**Comment by pasagame** [comment]
thank verry much.
