### ISSUE TITLE
โหลดLibrary TridentTD_LineNotify เเล้วเเต่ยังขึ้น error ครับ

### ISSUE THREAD

**Issue by DDD9696** [TridentTD/TridentTD_LineNotify#6]
นี่คื่อ error messages ครับ
Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

sketch_jan19a:1:10: error: TridentTD_LineNotify.h: No such file or directory

Multiple libraries were found for "TridentTD_LineNotify.h"
compilation terminated.

 Used: C:\Users\นพรัตน์มาร์ตี้\Documents\Arduino\libraries\TridentTD_LineNotify
 Not used: C:\Users\นพรัตน์มาร์ตี้\Documents\Arduino\libraries\TridentTD_LineNotify-master
exit status 1
TridentTD_LineNotify.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by TridentTD** [comment]
ArduinoIDE ไม่รู้จัก directory ชื่อไทย
ต้องตั้งชื่อ user เป็นภาษาอังกฤษครับ

ArduinoIDE ถึงจะเข้าถึง directory ของไลบรารี่ได้
