### ISSUE TITLE
รบกวนช่วยเพิ่มการใส่ Emoji ใน Message ให้หน่อยครับ

### ISSUE THREAD

**Issue by cychrn** [TridentTD/TridentTD_LineNotify#8]
สวัสดีครับ

พอดีผมจำเป็นต้องใช้ Emoji ควบคู่กับ ข้อความในการส่ง Line Notify น่ะครับ ไม่ทราบว่าพอจะสามารถเพิ่มฟีเจอร์นี้เข้าไปได้บ้างไหมครับ?

ผมพยายามหาดูนานมากแต่ก็ยังไม่พบว่าจะทำอย่างไรได้น่ะครับ เห็นแต่วิธีใช้ Emoji แบบดั้งเดิมที่ LINE เคยมีมี แต่เขาก็เขียนไว้ว่าเป็นวิธีที่ล้าหลังไปแล้วน่ะครับ

รบกวนผู้พัฒนาด้วยนะครับผม

ขอบคุณมากครับ

**Comment by cychrn** [comment]
ผมเจอเว็บที่เกี่ยวข้องตามนี้ครับ เผื่อเป็นข้อมูลให้ครับ

https://www.facebook.com/LINEDEVTH/photos/emoji-%E0%B8%AA%E0%B9%88%E0%B8%87%E0%B8%87%E0%B9%88%E0%B8%B2%E0%B8%A2%E0%B8%81%E0%B8%A7%E0%B9%88%E0%B8%B2%E0%B9%80%E0%B8%94%E0%B8%B4%E0%B8%A1-%E0%B9%84%E0%B8%A1%E0%B9%88%E0%B8%95%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B9%84%E0%B8%9B%E0%B9%81%E0%B8%9B%E0%B8%A5%E0%B8%87%E0%B9%82%E0%B8%84%E0%B9%89%E0%B8%94%E0%B9%83%E0%B8%AB%E0%B9%89%E0%B8%A2%E0%B8%B8%E0%B9%88%E0%B8%87%E0%B8%A2%E0%B8%B2%E0%B8%81%E0%B9%81%E0%B8%A5%E0%B9%89%E0%B8%A7%E0%B9%82%E0%B8%94%E0%B8%A2%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%AA%E0%B9%88%E0%B8%87-emoji-%E0%B9%83%E0%B8%99%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%84%E0%B8%A7/647346446110271/

https://l.facebook.com/l.php?u=https%3A%2F%2Fdevelopers.line.biz%2Fen%2Freference%2Fmessaging-api%2F%3Ffbclid%3DIwAR3k6aIiMdi7DNwZpN7wSip2sWlthANfHkLhmVZS2tDLFc-vVM_30CuAdow%23text-message&h=AT35a9dbLBiyZNKJlksGJcAgwgKUUTHC5DxN1uAj3guywVfZPrt-_GUuDqFvOLtCrSZUobcfUMaV_a4O4kX0RbQ3l_BzB-O_1Hg5ziS0bMLnlTOn6YETgT1nx_my_0UNfX7w&__tn__=-UK*F

**Comment by TridentTD** [comment]
ขอบคุณครับ ไว้เก็บเป็น feature ในรุ่นถัดๆไปให้ครับ

**Comment by TridentTD** [comment]
> ผมเจอเว็บที่เกี่ยวข้องตามนี้ครับ เผื่อเป็นข้อมูลให้ครับ
> 
> https://www.facebook.com/LINEDEVTH/photos/emoji-%E0%B8%AA%E0%B9%88%E0%B8%87%E0%B8%87%E0%B9%88%E0%B8%B2%E0%B8%A2%E0%B8%81%E0%B8%A7%E0%B9%88%E0%B8%B2%E0%B9%80%E0%B8%94%E0%B8%B4%E0%B8%A1-%E0%B9%84%E0%B8%A1%E0%B9%88%E0%B8%95%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B9%84%E0%B8%9B%E0%B9%81%E0%B8%9B%E0%B8%A5%E0%B8%87%E0%B9%82%E0%B8%84%E0%B9%89%E0%B8%94%E0%B9%83%E0%B8%AB%E0%B9%89%E0%B8%A2%E0%B8%B8%E0%B9%88%E0%B8%87%E0%B8%A2%E0%B8%B2%E0%B8%81%E0%B9%81%E0%B8%A5%E0%B9%89%E0%B8%A7%E0%B9%82%E0%B8%94%E0%B8%A2%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%AA%E0%B9%88%E0%B8%87-emoji-%E0%B9%83%E0%B8%99%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%84%E0%B8%A7/647346446110271/
> 
> https://l.facebook.com/l.php?u=https%3A%2F%2Fdevelopers.line.biz%2Fen%2Freference%2Fmessaging-api%2F%3Ffbclid%3DIwAR3k6aIiMdi7DNwZpN7wSip2sWlthANfHkLhmVZS2tDLFc-vVM_30CuAdow%23text-message&h=AT35a9dbLBiyZNKJlksGJcAgwgKUUTHC5DxN1uAj3guywVfZPrt-_GUuDqFvOLtCrSZUobcfUMaV_a4O4kX0RbQ3l_BzB-O_1Hg5ziS0bMLnlTOn6YETgT1nx_my_0UNfX7w&__tn__=-UK*F

เข้าไปดูตาม Link ที่ส่งมานี้
จะเป็น API สำหรับ LINE Messaging API (ว่าง่ายๆคือเอาไว้ทำ LINE Chat ) ครับ
สำหรับ API ในการทำ LINE Notify จะเป็นอีกส่วนนึง
ตาม LINE Notify API  Document 
ยังไม่สามารถใช้ emoji ใน LINE Notify ได้
ใช้ได้แต่ sticker ครับ

**Comment by cychrn** [comment]
ขอบคุณมากสำหรับการอัพเดทครับ เป็นกำลังใจให้นะครับ
