### ISSUE TITLE
คำสั่งnotify รับค่าจากตัวแปร String แล้ว ระบบ Restart

### ISSUE THREAD

**Issue by aotaot399** [TridentTD/TridentTD_LineNotify#9]
ใช้แบบนี้แล้ว ระบบ Restart
  String str = "55555";
  LINE.notify(str);

Log ใน Serial
---  CUT HERE FOR EXCEPTION DECODER ----

แต่
LINE.notify("55555"); ใช้แบบนนี้ไม่มีปัญหา

**Comment by RichJ123** [comment]
ใช่เลย เจอเหมือนกันครับ confirm ปัญหา ไม่ว่าจะส่งอะไรก็ restart หมดครับ
